### ISSUE TITLE
Silent eslint for "each" attribute of "for" statement

### ISSUE THREAD

**Issue by texttechne** [vkbansal/eslint-plugin-jsx-control-statements#1] opened 2016-01-09 13:10 UTC
Eslint complains about the following code: 

```
<For each="item" of={items}>
  <div>{item}</div>
</For>
```

Error is `error  "item" is not defined  no-undef`. Given what you have already implemented, this would solve AlexGilleran/jsx-control-statements/issues/7.

**Comment by vkbansal** [comment] 2016-01-09 13:12
Yes, I'm looking into it.

**Comment by vkbansal** [comment] 2016-01-09 16:56
must be fixed in v1.0

**Comment by khmelevskii** [comment] 2016-01-17 10:42
don't fixed for me

"jsx-control-statements": "1.1.1"
"eslint-plugin-jsx-control-statements": "1.0.2"
"babel": "5.8.34"

**Comment by vkbansal** [comment] 2016-01-17 13:02
It should work fine. Once check the installed version by running `npm ls --depth=0`

**Comment by GabiAxel** [comment] 2016-01-23 10:32
Doesn't work for me either. Added the plugin, rules and globals to .eslintrc. Installed versions:

babel-eslint@5.0.0-beta6
eslint@1.10.3
eslint-loader@1.2.0
eslint-plugin-jsx-control-statements@1.0.2
eslint-plugin-react@3.15.0

Can you please provide a package.json devDependencies part from a working example to help us compare versions?

**Comment by vkbansal** [comment] 2016-02-01 02:56
Check with latest version once

**Comment by GabiAxel** [comment] 2016-02-01 10:00
I upgraded to 1.1.0 but still getting the error. Can you please post example package.json and .eslintrc of a working case to help us compare?

**Comment by vkbansal** [comment] 2016-02-01 10:26
```
// package.json
    "eslint": "^1.10.3",
    "eslint-plugin-jsx-control-statements": "^1.1.0",
    "eslint-plugin-react": "^3.15.0",
```

```
// .eslintrc
    plugins: [
        "react",
        "jsx-control-statements"
    ],
    rules: {
        ....
        "jsx-control-statements/jsx-for-require-each": 1,
        "jsx-control-statements/jsx-for-require-index": 1,
        ....
    }
```

**Comment by GabiAxel** [comment] 2016-02-02 10:40
Apparently this was caused by "extends": ["eslint:recommended"] - the errors stopped after removing this. Thanks anyway.

**Comment by texttechne** [comment] 2016-02-02 14:27
@GabiAxel Would you be so kind to open another ticket. On the one hand we should find out what rule causes this bug. On the other hand it should at leat be documented.

**Comment by khmelevskii** [comment] 2016-02-14 23:53
Don't work if
`"parser": "babel-eslint",`

**Comment by fedevegili** [comment] 2016-02-22 14:01
The problem still occurs to me, usign the latest version. Is there any fix por this?

**Comment by texttechne** [comment] 2016-04-05 00:18
@vkbansal Could you reopen the ticket?

**Comment by patkirts** [comment] 2016-04-07 03:16
Hi, I'm also getting this error, both in Atom and from the command line, with up-to-date packages (.eslintrc rules same as above):

```
babel-eslint@6.0.2
eslint@2.7.0
eslint-plugin-jsx-control-statements@1.1.0
```

Any help I can offer solving this?

**Comment by vkbansal** [comment] 2016-04-07 05:32
As reported by @GabiAxel, I believe that some rule from `eslint:recommended` is causing this issue. You can help in identifying it.

**Comment by patkirts** [comment] 2016-04-07 06:10
Well, I'm not explicitly using `eslint:recommended`, so I manually toggled every rule in the list, which didn't change anything. Then I commented out every rule in my .eslintrc other than `no-undef` and the rules from this package. Still getting the error. Removed `babel-eslint`, still getting the error. I don't see anything in the source that looks wrong, but I'll keep digging.

**Comment by anjianshi** [comment] 2016-04-10 03:01
meet same problem.

```
"eslint": "^2.7.0",
"eslint-plugin-jsx-control-statements": "^1.1.0",
"eslint-plugin-react": "^4.3.0",
"babel-eslint": "^6.0.2",
```

disable `babel-eslint` parser can temporarily fix it.

**Comment by AlexGilleran** [comment] 2016-04-15 06:48
So I had a crack at this over in https://github.com/vkbansal/eslint-plugin-jsx-control-statements/pull/10.

I can't see how this can really be done without disabling the `no-undef` rule that causes it and replacing it completely, so that's what I've done. As far as I can tell ESLint is great at letting you add new rules but not poke holes in existing ones :(.

**Comment by vkbansal** [comment] 2016-04-18 01:42
Should be fixed in v2.1.0.

Please let me know if it does.

**Comment by patkirts** [comment] 2016-04-18 13:56
I can confirm that it's working for me. Thank you!

**Comment by vkbansal** [comment] 2016-04-19 05:35
OK. I'll close this then.

**Closed as completed by vkbansal** 2016-04-19 05:35 UTC
